server:
  #端口
  port: 8081
  #  servlet:
  #上下文路径
#    context-path: /qz

#thymeleaf模板配置
spring:
  thymeleaf:
    cache: false

  # 配置静态路径（默认为public/static路径）
  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true # 开启静态资源策略管理
            paths: /** # 针对的静态资源路径




